import type { AnalysisResult } from "../core/analyzer.js";

export const PR_COMMENT_MARKER = "<!-- dep-brain-report -->";

export interface PrCommentOptions {
  hasBaseline?: boolean;
}

export function renderPrCommentReport(
  result: AnalysisResult,
  options: PrCommentOptions = {}
): string {
  const lines: string[] = [
    PR_COMMENT_MARKER,
    "## Dependency Brain",
    "",
    `**Policy:** ${result.policy.passed ? "PASS" : "FAIL"}`,
    `**Project Health:** ${result.score}/100`,
    `**Findings:** duplicates ${result.duplicates.length}, unused ${result.unused.length}, outdated ${result.outdated.length}, risks ${result.risks.length}`
  ];

  if (options.hasBaseline) {
    const counts = result.newFindings?.counts ?? {
      duplicates: result.duplicates.length,
      unused: result.unused.length,
      outdated: result.outdated.length,
      risks: result.risks.length
    };
    lines.push(
      `**New since baseline:** duplicates ${counts.duplicates}, unused ${counts.unused}, outdated ${counts.outdated}, risks ${counts.risks}`
    );
  }

  if (result.policy.reasons.length > 0) {
    lines.push("");
    lines.push("### Policy Reasons");
    for (const reason of result.policy.reasons) {
      lines.push(`- ${reason}`);
    }
  }

  if (result.topIssues.length > 0) {
    lines.push("");
    lines.push("### Top Issues");
    for (const item of result.topIssues.slice(0, 5)) {
      lines.push(
        `- **${item.priority.toUpperCase()}** ${item.kind} \`${item.name}\`${item.package ? ` [${item.package}]` : ""}: ${item.summary}`
      );
    }
  }

  const upgradePriorities = summarizeUpgradePriorities(result);
  if (upgradePriorities) {
    lines.push("");
    lines.push("### Upgrade Priorities");
    lines.push(upgradePriorities);
  }

  lines.push("");
  lines.push("_Generated by dep-brain._");
  return lines.join("\n");
}

function summarizeUpgradePriorities(result: AnalysisResult): string {
  const counts = result.outdated.reduce(
    (acc, item) => {
      acc[item.advice.risk] += 1;
      return acc;
    },
    { high: 0, medium: 0, low: 0 }
  );

  return [`high ${counts.high}`, `medium ${counts.medium}`, `low ${counts.low}`]
    .filter((entry) => !entry.endsWith(" 0"))
    .join(", ");
}
