import type { AnalysisResult } from "../core/analyzer.js";

export const PR_COMMENT_MARKER = "<!-- dep-brain-report -->";

export interface PrCommentOptions {
  hasBaseline?: boolean;
}

export async function renderPrCommentReport(
  result: AnalysisResult,
  options: PrCommentOptions = {}
): Promise<string> {
  const { auditLicenses } = await import("../core/licenses.js");
  let licenseSummary = "";
  try {
    const licenseAudit = await auditLicenses(result.rootDir);
    licenseSummary = `**License Compliance:** ${licenseAudit.packages.length} audited, ${licenseAudit.counts.allowed} approved, ${licenseAudit.counts.denied} denied, ${licenseAudit.counts.unknown} unknown.`;
  } catch (err) {
    licenseSummary = "**License Compliance:** Failed to run audit.";
  }

  const lines: string[] = [
    PR_COMMENT_MARKER,
    "## Dependency Brain",
    "",
    `**Policy:** ${result.policy.passed ? "PASS" : "FAIL"}`,
    `**Project Health:** ${result.score}/100`,
    `**Findings:** duplicates ${result.duplicates.length}, unused ${result.unused.length}, outdated ${result.outdated.length}, risks ${result.risks.length}`,
    licenseSummary
  ];

  if (options.hasBaseline) {
    const counts = result.newFindings?.counts ?? {
      duplicates: result.duplicates.length,
      unused: result.unused.length,
      outdated: result.outdated.length,
      risks: result.risks.length
    };
    lines.push(
      `**New since baseline:** duplicates ${counts.duplicates}, unused ${counts.unused}, outdated ${counts.outdated}, risks ${counts.risks}`
    );

    const newRisks = result.newFindings?.risks ?? [];
    if (newRisks.length > 0) {
      lines.push("");
      lines.push("#### ⚠️ New Risky Dependencies Since Baseline");
      for (const item of newRisks) {
        lines.push(`- **${item.name}** (Trust: ${item.trustScore.toUpperCase()}): ${item.reasons.join("; ")}`);
      }
    }
  }

  if (result.policy.reasons.length > 0) {
    lines.push("");
    lines.push("### Policy Reasons");
    for (const reason of result.policy.reasons) {
      lines.push(`- ${reason}`);
    }
  }

  if (result.topIssues.length > 0) {
    lines.push("");
    lines.push("### Top Issues");
    for (const item of result.topIssues.slice(0, 5)) {
      const ownersStr = item.owners && item.owners.length > 0 ? ` [owners: ${item.owners.join(", ")}]` : "";
      lines.push(
        `- **${item.priority.toUpperCase()}** ${item.kind} \`${item.name}\`${item.package ? ` [${item.package}]` : ""}${ownersStr}: ${item.summary}`
      );
    }
  }

  const upgradePriorities = summarizeUpgradePriorities(result);
  const vulnerabilityCount = result.risks.reduce(
    (total, item) => total + item.riskFactors.vulnerabilities.length,
    0
  );
  if (upgradePriorities) {
    lines.push("");
    lines.push("### Upgrade Priorities");
    lines.push(upgradePriorities);
  }

  if (vulnerabilityCount > 0) {
    lines.push("");
    lines.push("### Vulnerabilities");
    lines.push(`${vulnerabilityCount} OSV advisories found.`);
  }

  lines.push("");
  lines.push("_Generated by dep-brain._");
  return lines.join("\n");
}

function summarizeUpgradePriorities(result: AnalysisResult): string {
  const counts = result.outdated.reduce(
    (acc, item) => {
      acc[item.advice.risk] += 1;
      return acc;
    },
    { high: 0, medium: 0, low: 0 }
  );

  return [`high ${counts.high}`, `medium ${counts.medium}`, `low ${counts.low}`]
    .filter((entry) => !entry.endsWith(" 0"))
    .join(", ");
}
